[package]
name = "actix-redis"
version = "0.1.0"
authors = ["Cheng JIANG <jiang.cheng@vip.163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
bb8-redis = "0.5.0"
log = "0.4.11"
backoff = "0.2.1"
